schema:
  - './src/temp/GraphQLIntrospectionResultGithub.json'
documents: 'src/**/*.github.graphql'
plugins:
  - typescript
  - typescript-operations
  - typed-document-node

cacheDir: .generated
config:
    useIndexSignature: true
